full_name = input("\n\n\t\t\t\t\t Bio-Data \n\n\t Name: ")
gender = input("\t Gender: ")
age = input("\t Age: ")
BDate = input("\t Date of Birth: ")
BPlace = input("\t Birth Place: ")
Height = input("\t Height(ft): ")
Weight = input("\t Weight(kg): ")
Btype = input("\t Blood Type: ")

StrtAd = input("\t Street name: ")
Sub_CompAd = input("\t Subdivision/Compound/Village: ")
Brgy = input("\t Barangay name: ")
CitAd = input("\t City Name: ")
ProvAd = input("\t Provincial Name: ")
Zip = input("\t Zip Code: ")
CvStatus = input("\t Civil Status: ")
Nat = input("\t Nationality: ")
Rel = input("\t Religion: ")

LgKnown = input("\t Language/s known: ")
Hobby = input("\t At least 2 Hobbies related to IT: ")
Sk = input("\t Skills: ")

EDetails = input("\n\t\t\t\t EDUCATIONAL BACKGROUND ")
ESch = input("\n\t Elementary School name: ")
HSch = input("\t High School name: ")
Col = input("\t College School name: ")
Cou = input("\t Chosen Course: ")
Sec = input("\t Section's name: ")

FBg = input("\n\t\t\t\t FAMILY DETAILS")
Fn = input("\t Father's name: ")
Fcn = input("\t Contact No.: ") 
Mn = input("\t Mother's name: ")
Mcn = input("\t Contact No.: ")

CtD = input("\n\t\t\t\t CONTACT DETAILS ")
ConDe = input("\t Contact No.: ")
ConD = input("\t E-mail Address: ")

print("\n\n\n\n\t\t\t\t Hi, I am" , full_name, gender , "and I am" , age , "years old. I was born on" , BDate , "at" , BPlace, ". \n\t I am" , Height , "tall and weighs", Weight , "with a blood type of" , Btype , ". I live in", StrtAd, Brgy, CitAd, "," , Zip, ", in" , ProvAd , ". \n\t My status is \t" , CvStatus , ", and i'm a" , Nat , "and is a " , Rel , ". I know" , LgKnown , "and my hobbies are" , Hobby , "while my \n\t skills are" , Sk , ". \n\t\t\t I finished my primary education at" , ESch , ", while my secondary education happened at" , HSch , ". \n\t I'm currently studying at" , Col, "with a course" , Cou , ", in section", Sec , ". \n\t My father is" , Fn , "and my mother is" , Mn, ".  You can contact me with my cellphone number," , ConDe , "and an e-mail of \n\t" , ConD,"." )
